"""Prepare writable analysis copies with read-only NAS inputs linked separately."""
import argparse
import os
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def link(source, destination, missing):
    if not source.exists():
        missing.append(str(source))
        return
    if destination.is_symlink() and destination.resolve() == source.resolve():
        return
    if destination.exists() or destination.is_symlink():
        raise FileExistsError(f"Refusing to replace {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.symlink_to(source, target_is_directory=source.is_dir())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nas-root", type=Path, default=Path(os.environ.get("VQ_NAS_ROOT", "/megaverse/storage/nasiri")))
    parser.add_argument("--workspace", type=Path, required=True)
    args = parser.parse_args()
    workspace = args.workspace.resolve()
    if workspace == REPO or workspace == REPO / "notebooks":
        parser.error("Choose a separate writable workspace, for example work/analysis")
    notebooks = workspace / "notebooks"
    notebooks.mkdir(parents=True, exist_ok=True)
    for source in (REPO / "notebooks").rglob("*.ipynb"):
        destination = notebooks / source.relative_to(REPO / "notebooks")
        if destination.exists():
            if destination.read_bytes() == source.read_bytes():
                continue
            raise FileExistsError(f"Preserve existing work or choose a new workspace: {destination}")
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    jupyter = args.nas_root.resolve() / "jupyter"
    archive = jupyter / "vq-explore"
    missing = []
    for name in ("code_usage_results", "end_to_end_results"):
        link(archive / name, workspace / name, missing)
    link(archive / "notebooks/data", notebooks / "data", missing)
    link(archive / "notebooks/chapter9_outputs/data/raw", notebooks / "chapter9_outputs/data/raw", missing)
    # RQ1 uses the clean per-image rows generated by RQ2. Copy this input so the
    # RQ2 notebook can subsequently regenerate it without altering the archive.
    paired_rows = archive / "notebooks/chapter5_outputs/data/ch05_psnr_rows.csv"
    target = notebooks / "chapter5_outputs/data/ch05_psnr_rows.csv"
    if paired_rows.exists() and not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(paired_rows, target)
    print(f"Prepared {notebooks}")
    print(f"Set VQ_NAS_ROOT={args.nas_root.resolve()} before running notebooks.")
    if missing:
        print("Missing archived inputs:\n" + "\n".join(missing))
        raise SystemExit(1)


if __name__ == "__main__":
    main()
